package muss.stein.memefactory.util

import muss.stein.memefactory.R

object Constants {

    val TEMPLATE_LIST= listOf(
        R.drawable.batman_slapping_robin,
        R.drawable.change_my_mind,
        R.drawable.mocking_spongebob,
        R.drawable.two_buttons,
        R.drawable.blank_template,
        R.drawable.anakin_padme,
        R.drawable.bike_fall,
        R.drawable.boardroom_meeting_suggestion,
        R.drawable.brain_awake_at_night,
        R.drawable.clown_applying_makeup,
        R.drawable.expanding_brain,
        R.drawable.flex_tape,
        R.drawable.futurama_fry,
        R.drawable.grus_plan,
        R.drawable.guy_holding_cardboard_sign,
        R.drawable.hard_to_swallow_pills,
        R.drawable.i_bet_hes_thinking_about_other_women,
        R.drawable.laughing_leo,
        R.drawable.one_does_not_simply,
        R.drawable.panik_kalm_panik,
        R.drawable.sad_pablo_escobar,
        R.drawable.surprised_pikachu,
        R.drawable.the_rock_driving,
        R.drawable.the_scroll_of_truth,
        R.drawable.trump_bill_signing,
        R.drawable.tuxedo_winnie_the_pooh,
        R.drawable.unsettled_tom,
        R.drawable.wait_you_guys,
        R.drawable.afraid_to_ask,
        R.drawable.bad_luck_brian,
        R.drawable.brace_yourselves_x_is_coming,
        R.drawable.buff_doge_vs_cheems,
        R.drawable.drake_hotline_bling,
        R.drawable.dumbest_man,
        R.drawable.hide_the_pain_harold,
        R.drawable.jim_halpert_explains,
        R.drawable.lisa_spot_light,
        R.drawable.running_away_balloon,
        R.drawable.sponge_bob_reading_paper,
        R.drawable.stepped_on_shit,
        R.drawable.that_would_be_great,
        R.drawable.this_is_worthless,
        R.drawable.x_x_everywhere,
        R.drawable.wolwerine_and_photo,
        R.drawable.after_all_why_not,
        R.drawable.alien_nextto_a_grave,
        R.drawable.big_book_small_book,
        R.drawable.billy_what_have_you_done,
        R.drawable.blank_starter_pack,
        R.drawable.blank_throphy,
        R.drawable.bugs_bunny_no,
        R.drawable.crying_peter_parker,
        R.drawable.dude_wtf,
        R.drawable.guess_i_will_die,
        R.drawable.keep_kalm,
        R.drawable.no_others_wrong,
        R.drawable.ol_reliable,
        R.drawable.sleeping_squidward
    )
}